### ISSUE TITLE
Doesn't display map

### ISSUE THREAD

**Issue by luvemil** [vranki/ExtPlane-Panel#16]
Neither maps/gps nor maps/radar display anything other than the heading. Any fix available? Source is Google Maps.

**Comment by markcellis** [comment]
I'm working on this. The problem is that the Google Maps API key is no longer valid. Given the restrictions on the Google Maps API I was thinking it might be a good idea to allow users to get their own key and put that in as a property.

I have it working again now with my own key but I think with a single key it is possible that we would hit the limit of maps hits in a 24 hour period.

Thoughts?

**Comment by dankrusi** [comment]
Hi, I've updated the API key to a new one, added a setting so you can input your own key, and added a note on keys.

See https://github.com/vranki/ExtPlane-Panel/commit/e5bf22c3aaff2d1da9d3c6353ef88d905193186f and https://developers.google.com/maps/documentation/static-maps/

**Comment by markcellis** [comment]
Excellent, that is the way I would have done it too.

 

Mark
